name: Hello world
on:
  push:
    branches:
      - master
jobs:
  check-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check OS
        run: |
          if [ "$(uname)" == "Darwin" ]; then
            echo "This is macOS"
          elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
            echo "This is Linux"
          elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
            echo "This is Windows"
          else
            echo "Unknown OS"
          fi
